;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        coffee-dedent-line-backspace
        downcase-region
        electric-pair-delete-pair
        indent-for-tab-command
        kill-region
        zencoding-expand-line
        ))

(setq mc/cmds-to-run-once
      '(
        inline-string-rectangle
        js2-mode-show-node
        tab-to-tab-stop
        yas-expand
        ))
